In [6]:
import numpy as np

In [7]:
myList = [0,1,2,3,4]

In [9]:
arr = np.array([0,1,2,3,4])

In [10]:
myList

[0, 1, 2, 3, 4]

In [11]:
arr

array([0, 1, 2, 3, 4])

In [12]:
newArr = np.array(myList)

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
anotherList = [[1,2,3],[4,5,6],[7,8,9]]

In [21]:
anotherList[0]

[1, 2, 3]

In [23]:
newArray = np.array(anotherList)

In [24]:
newArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
newArray[1]

array([4, 5, 6])

In [26]:
newArray[1][2]

6

In [27]:
newArray[1,2]

6

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand()

0.45921931604231725

In [31]:
a = np.random.rand(10)

In [32]:
a.shape

(10,)

In [33]:
np.eye(7).shape

(7, 7)

In [35]:
np.random.randn(10)

array([ 0.45716176,  0.05100842,  0.15864533,  0.82392811, -1.13535589,
       -1.06066595, -0.43663076,  1.18480264,  0.8659301 ,  1.1247667 ])

In [37]:
np.random.randint(0,100,7)

array([65,  9, 50, 76, 78, 95, 30])

In [39]:
arr = np.random.randint(0,100,30)

In [41]:
arr.shape

(30,)

In [42]:
arr.reshape(5,6)

array([[54, 68, 49, 27, 99, 55],
       [23,  0, 60, 76, 22, 49],
       [32, 80, 48, 19,  1, 81],
       [73, 42, 57, 89, 11, 78],
       [ 4, 28, 33, 15, 59, 37]])

In [43]:
arr

array([54, 68, 49, 27, 99, 55, 23,  0, 60, 76, 22, 49, 32, 80, 48, 19,  1,
       81, 73, 42, 57, 89, 11, 78,  4, 28, 33, 15, 59, 37])

In [44]:
arr.max()

99

In [45]:
arr.min()

0

In [46]:
arr.argmax()

4

In [47]:
arr.argmin()

7

In [49]:
arr[7]

0

In [50]:
arr[:3]

array([54, 68, 49])

In [51]:
arr[5:]

array([55, 23,  0, 60, 76, 22, 49, 32, 80, 48, 19,  1, 81, 73, 42, 57, 89,
       11, 78,  4, 28, 33, 15, 59, 37])

In [52]:
arr[10:15]

array([22, 49, 32, 80, 48])

In [53]:
slice_of_an_array = arr[10:15]

In [54]:
slice_of_an_array

array([22, 49, 32, 80, 48])

In [56]:
slice_of_an_array[:] = 100

In [57]:
slice_of_an_array

array([100, 100, 100, 100, 100])

In [58]:
arr

array([ 54,  68,  49,  27,  99,  55,  23,   0,  60,  76, 100, 100, 100,
       100, 100,  19,   1,  81,  73,  42,  57,  89,  11,  78,   4,  28,
        33,  15,  59,  37])

In [59]:
newArray = arr.copy()

In [61]:
newArray[:]= 200

In [62]:
newArray

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200])

In [63]:
arr

array([ 54,  68,  49,  27,  99,  55,  23,   0,  60,  76, 100, 100, 100,
       100, 100,  19,   1,  81,  73,  42,  57,  89,  11,  78,   4,  28,
        33,  15,  59,  37])

In [64]:
arr > 20

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False,  True,  True])

In [66]:
myList > 20

TypeError: ignored

In [67]:
boolArray = arr > 20

In [68]:
boolArray

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False,  True,  True])

In [69]:
arr

array([ 54,  68,  49,  27,  99,  55,  23,   0,  60,  76, 100, 100, 100,
       100, 100,  19,   1,  81,  73,  42,  57,  89,  11,  78,   4,  28,
        33,  15,  59,  37])

In [70]:
arr[boolArray]

array([ 54,  68,  49,  27,  99,  55,  23,  60,  76, 100, 100, 100, 100,
       100,  81,  73,  42,  57,  89,  78,  28,  33,  59,  37])

In [71]:
arr[arr>20]

array([ 54,  68,  49,  27,  99,  55,  23,  60,  76, 100, 100, 100, 100,
       100,  81,  73,  42,  57,  89,  78,  28,  33,  59,  37])

In [72]:
arr + arr

array([108, 136,  98,  54, 198, 110,  46,   0, 120, 152, 200, 200, 200,
       200, 200,  38,   2, 162, 146,  84, 114, 178,  22, 156,   8,  56,
        66,  30, 118,  74])

In [73]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
arr * arr

array([ 2916,  4624,  2401,   729,  9801,  3025,   529,     0,  3600,
        5776, 10000, 10000, 10000, 10000, 10000,   361,     1,  6561,
        5329,  1764,  3249,  7921,   121,  6084,    16,   784,  1089,
         225,  3481,  1369])

In [76]:
arr + 100

array([154, 168, 149, 127, 199, 155, 123, 100, 160, 176, 200, 200, 200,
       200, 200, 119, 101, 181, 173, 142, 157, 189, 111, 178, 104, 128,
       133, 115, 159, 137])

In [77]:
arr *5

array([270, 340, 245, 135, 495, 275, 115,   0, 300, 380, 500, 500, 500,
       500, 500,  95,   5, 405, 365, 210, 285, 445,  55, 390,  20, 140,
       165,  75, 295, 185])

In [78]:
1/0

ZeroDivisionError: ignored

In [79]:
arr / arr

<ipython-input-79-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1., nan,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [81]:
arr[0] = 0

In [82]:
arr

array([  0,  68,  49,  27,  99,  55,  23,   0,  60,  76, 100, 100, 100,
       100, 100,  19,   1,  81,  73,  42,  57,  89,  11,  78,   4,  28,
        33,  15,  59,  37])

In [83]:
arr / arr

<ipython-input-83-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1., nan,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [84]:
np.sqrt(arr)

array([ 0.        ,  8.24621125,  7.        ,  5.19615242,  9.94987437,
        7.41619849,  4.79583152,  0.        ,  7.74596669,  8.71779789,
       10.        , 10.        , 10.        , 10.        , 10.        ,
        4.35889894,  1.        ,  9.        ,  8.54400375,  6.4807407 ,
        7.54983444,  9.43398113,  3.31662479,  8.83176087,  2.        ,
        5.29150262,  5.74456265,  3.87298335,  7.68114575,  6.08276253])

In [85]:
np.exp(arr)

array([1.00000000e+00, 3.40427605e+29, 1.90734657e+21, 5.32048241e+11,
       9.88903032e+42, 7.69478527e+23, 9.74480345e+09, 1.00000000e+00,
       1.14200739e+26, 1.01480039e+33, 2.68811714e+43, 2.68811714e+43,
       2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 1.78482301e+08,
       2.71828183e+00, 1.50609731e+35, 5.05239363e+31, 1.73927494e+18,
       5.68572000e+24, 4.48961282e+38, 5.98741417e+04, 7.49841700e+33,
       5.45981500e+01, 1.44625706e+12, 2.14643580e+14, 3.26901737e+06,
       4.20121040e+25, 1.17191424e+16])